CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_ZMK_STUDIO=n
 
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Debug logging
CONFIG_USB_CDC_ACM=y
CONFIG_ZMK_USB_LOGGING=y
